---
title: "Yeast Gene Imputation"
author: "M.Soria"
date: "19/10/2020"
output: html_document
---

</br>

***

##### The following code imputes function on genes from Sacharromyces cerevisiae. 

***

</br>


### 11. Functions for Cluster Analysis 
```{r echo=TRUE}

# This function's output is a nested list with of the genes grouped per cluster and their corresponding correlation values. Inputs:
# x = logcounts (normalized gene counts from RNA seq)
# y = clusters (matrix of genes w/ cluster number)
# clust_total = total number of clusters

corr_per_clust <- function(x, y, clust_total){
  corr_cl <- list()
  for (i in 1:clust_total){
    clusterX <- y[y$ClusterNumber == i,]
    cluster_list <- as.list(clusterX$GeneID)
    cluster <- x[rownames(x) %in% cluster_list,]
    corr_result <- cor(t(cluster))
    corr_cl[[paste0("Cluster", i)]] <- corr_result
  }
  return(corr_cl)
}

corr_allClusters <- corr_per_clust(logcounts, clusters, 100)


# This function's output is a list of data frames containing all GO terms associated with the genes belonging to a cluster. Input:
# x = scerevisiae_GO_matrix_wide (matrix of genes belonging to a GO term)
# y = clusters (matrix of genes w/ cluster number)
# clust_total = total number of clusters

GO_per_cl <- function(x,y,clust_total){
  GO_cl <- list()
  for (i in 1:clust_total){
    clusterX <- y[y$ClusterNumber == i,]
    cluster_list <- as.list(clusterX$GeneID)
    cluster_GOterms <- x[x$GeneID %in% cluster_list,]
    rownames(cluster_GOterms)<- cluster_GOterms[,1] 
    cluster_GOterms[,1] <- c()
    cluster_GOterms <- cluster_GOterms[,which(colSums(cluster_GOterms) > 0)]
    GO_cl[[paste0("Cluster", i)]] <- cluster_GOterms
  }
  return(GO_cl)
}

GOterms_allClusters <- GO_per_cl(scerevisiae_GO_matrix_wide, clusters, 100)


# This function's output is a nested list of genes belonging to a cluster with their corresponding weighted correlations. Input:
# gene_list = list of genes to be correlated; corr_cl = correlation values for cluster
# cl_GO = GO terms for cluster

wcorr_cluster <- function(gene_list, corr_cl, cl_GO){
  wcorr_result <- list()
  
  for (i in gene_list){
    corr_value <- corr_cl[i,]
    corr_value_df <- as.data.frame(corr_value)
    weighted_go <- merge(corr_value_df, cl_GO, by = "row.names")
    rownames(weighted_go) <- weighted_go[,1]
    weighted_go[,1] <- c()
    weighted_go <- weighted_go[,1]*weighted_go[,2:ncol(weighted_go)]
    normalized_weighted_go <- colSums(weighted_go)/nrow(weighted_go)
    wcorr_result[[i]] <- normalized_weighted_go
  }
  setNames(wcorr_result, paste0(i))
  return(wcorr_result)
}

cluster1_wGO <- wcorr_cluster(is_blind, corr_cluster1, cluster1_GO_terms)


# Sum of corr values are used as a denominator in normalized_weighted_go
wcorr2_cluster <- function(gene_list, corr_cl, cl_GO){
  wcorr_result <- list()
  
  for (i in gene_list){
    corr_value <- corr_cl[i,]
    corr_value_df <- as.data.frame(corr_value)
    weighted_go <- merge(corr_value_df, cl_GO, by = "row.names")
    rownames(weighted_go) <- weighted_go[,1]
    weighted_go[,1] <- c()
    # this is where this differs from the original function. The sum of the correlation values for         gene1 in the gene_list is used as the denominator for the normalized_weighted_go object instead of     the nrow of the dataframe. This follows the formula of the weighted average, assuming that the corr     values are the "weights" 
    corr_colsum <- sum(weighted_go[,1])
    weighted_go <- weighted_go[,1]*weighted_go[,2:ncol(weighted_go)]
    normalized_weighted_go <- colSums(weighted_go)/corr_colsum
    wcorr_result[[i]] <- normalized_weighted_go
  }
  setNames(wcorr_result, paste0(i))
  return(wcorr_result)
}

cluster1_wGO2 <- wcorr2_cluster(is_blind, corr_cluster1, cluster1_GO_terms)




```
</br>

### 12. Cluster Analysis
```{r}
# Prepare Cluster data frame
clusters <- as.data.frame(mycl)
colnames(clusters) <- "ClusterNumber"

# make a new column, GeneID, from rownames
clusters$GeneID <- rownames(clusters)

# Grouping genes by cluster (using cluster 1)
cluster1 <- clusters[clusters$ClusterNumber == 1,] 
cluster1_list <- cluster1$GeneID

# look for cluster gene match in GO dictionary and subset nonzero columns 
cluster1_GO <- scerevisiae_GO_matrix_wide[scerevisiae_GO_matrix_wide$GeneID %in% cluster1_list,] 
cluster1_GO_nonzero <- cluster1_GO[, !apply(cluster1_GO == 0, 2, all)]

# Correlation in Cluster 1  (Function counterpart: corr_per_clust)
cluster_1 <- logcounts[rownames(logcounts) %in% cluster1_list,]
corr_cluster1 <- cor(t(cluster_1))

# GO terms for cluster 1 (Function counterpart: GO_per_cl)
cluster1_GO_terms <- scerevisiae_GO_matrix_wide[scerevisiae_GO_matrix_wide$GeneID %in% cluster1_list,]
rownames(cluster1_GO_terms)<- cluster1_GO_terms[,1] 
cluster1_GO_terms[,1] <- c()
cluster1_GO_terms <- cluster1_GO_terms[,which(colSums(cluster1_GO_terms) > 0)]

# weighted correlation for Cluster 1 (Function counterpart: wcorr_cluster)
is_blind <- cluster1_list[cluster1_list %in% dict_blind$blind]
blind_gene1 <- is_blind[1]

# Subset the row which contains blilnd_gene1 and turn it into a data frame
corr_value_blind1 <- corr_cluster1[blind_gene1,]
corr_value_blind1_df <- as.data.frame(corr_value_blind1)

# Merge the GO terms data frame for cluster 1 and the correlation values for blilnd_gene1 
weighted_go_cluster1 <- merge(corr_value_blind1_df, cluster1_GO_terms, by = "row.names")
rownames(weighted_go_cluster1) <- weighted_go_cluster1[,1]
weighted_go_cluster1[,1] <- c()
corr_colsum <- sum(weighted_go_cluster1[,1])
weighted_go_cluster1 <- weighted_go_cluster1[,1]*weighted_go_cluster1[,2:ncol(weighted_go_cluster1)]
normalized_weighted_go_cluster1 <- colSums(weighted_go_cluster1)/corr_colsum 
hist(normalized_weighted_go_cluster1)


# Use function, wcorr_cluster, to get the weighted values for all blinded genes in cluster 1
cluster1_wGO <- wcorr_cluster(is_blind, corr_cluster1, cluster1_GO_terms)

# Determining threshold based on histogram
hist(cluster1_wGO$YPR002W)
imputed_GO_terms <- names(which(normalized_weighted_go_cluster1 > 0.1))

# Convert output into a data frame with columns as GO terms and rows as gene names
cluster1_wGO_df <- as.data.frame(do.call(rbind, cluster1_wGO))
cluster1_wGO_df <- cluster1_wGO_df[order(rownames(cluster1_wGO_df)),]
cluster1_wGO_df <- cluster1_wGO_df[,order(colnames(cluster1_wGO_df))]

# using 0.1 as threshold
Clust1_threshold <- 0.005

imputed_Clust1_df_v2 <- (as.matrix(cluster1_wGO_df) > Clust1_threshold)*1
imputed_Clust1_df <- (as.matrix(cluster1_wGO_df) > Clust1_threshold)*1



# Filter original GO matrix to include only the genes of interest and the GO terms from the imputed df
# Filter by row
cluster1_inputMat <- scerevisiae_GO_matrix_wide[scerevisiae_GO_matrix_wide$GeneID %in% rownames(imputed_Clust1_df),]
rownames(cluster1_inputMat) <- cluster1_inputMat[,1]
cluster1_inputMat[,1] = c()
# Filter by column
cluster1_inputMat <- cluster1_inputMat[,colnames(cluster1_inputMat) %in% colnames(imputed_Clust1_df)]
# Order by row names and column names
cluster1_inputMat1 <- cluster1_inputMat[order(rownames(cluster1_inputMat)),]
cluster1_inputMat1 <- cluster1_inputMat[,order(colnames(cluster1_inputMat))]


# Filter imputed_Clust1_df object to include the genes and GO terms of cluster1_inputMat object above
imputed_Clust1_trim <- imputed_Clust1_df[rownames(imputed_Clust1_df_v2) %in% rownames(cluster1_inputMat),]
# Order by row names for direct comparison
imputed_Clust1_trim <- imputed_Clust1_trim[order(rownames(imputed_Clust1_trim)),]


# Comparison between input df and resultant df
Clust1_inutVSimputed <- ifelse(cluster1_inputMat == imputed_Clust1_trim, TRUE, FALSE)

# Negative 1 values appear for threshold > 0.005
Clust1_subtract <- imputed_Clust1_trim - cluster1_inputMat
which(Clust1_subtract == -1)

```
</br>

### Using wcorr2_cluster
```{r echo=TRUE}

cluster1_wGO2 <- wcorr2_cluster(is_blind, corr_cluster1, cluster1_GO_terms)

# Convert output into a data frame with columns as GO terms and rows as gene names
cluster1_wGO2_df <- as.data.frame(do.call(rbind, cluster1_wGO2))
cluster1_wGO2_df <- cluster1_wGO2_df[order(rownames(cluster1_wGO2_df)),]
cluster1_wGO2_df <- cluster1_wGO2_df[,order(colnames(cluster1_wGO2_df))]

# using 0.01 as threshold
Clust1_threshold <- 0.01

imputed_Clust1_df <- as.data.frame(sapply(cluster1_wGO2_df, function(x){
   as.numeric(x > Clust1_threshold)
  }))
row.names(imputed_Clust1_df) <- row.names(cluster1_wGO2_df)

# Filter original GO matrix to include only the genes of interest and the GO terms from the imputed df
# Filter by row
cluster1_inputMat <- scerevisiae_GO_matrix_wide[scerevisiae_GO_matrix_wide$GeneID %in% rownames(imputed_Clust1_df),]
rownames(cluster1_inputMat) <- cluster1_inputMat[,1]
cluster1_inputMat[,1] = c()
# Filter by column
cluster1_inputMat <- cluster1_inputMat[,colnames(cluster1_inputMat) %in% colnames(imputed_Clust1_df)]
# Order by row names and column names
cluster1_inputMat1 <- cluster1_inputMat[order(rownames(cluster1_inputMat)),]
cluster1_inputMat1 <- cluster1_inputMat[,order(colnames(cluster1_inputMat))]


# Filter imputed_Clust1_df object to include the genes and GO terms of cluster1_inputMat object above
imputed_Clust1_trim <- imputed_Clust1_df[rownames(imputed_Clust1_df) %in% rownames(cluster1_inputMat),]
# Order by row names for direct comparison
imputed_Clust1_trim <- imputed_Clust1_trim[order(rownames(imputed_Clust1_trim)),]
imputed_Clust1_trim <- imputed_Clust1_trim[,order(colnames(imputed_Clust1_trim))]

# Comparison between input df and resultant df
Clust1_inutVSimputed <- ifelse(cluster1_inputMat == imputed_Clust1_trim, TRUE, FALSE)

# Negative 1 values appear for threshold > 0.01
Clust1_subtract <- imputed_Clust1_trim - cluster1_inputMat
which(Clust1_subtract == -1)

```
</br>

### Using cluster 3
```{r echo=TRUE}

corr_cluster3 <- corr_allClusters$Cluster3
cluster3_GO_terms <- GOterms_allClusters$Cluster3
cluster3_list <- rownames(cluster3_GO_terms)
# Make a function to list all blind genes in a cluster
clust3_blind <- cluster3_list[cluster3_list %in% dict_blind$blind]

cluster3_wGO2 <- wcorr2_cluster(clust3_blind, corr_cluster3, cluster3_GO_terms)

# Convert output into a data frame with columns as GO terms and rows as gene names
cluster3_wGO2_df <- as.data.frame(do.call(rbind, cluster3_wGO2))
cluster3_wGO2_df <- cluster3_wGO2_df[order(rownames(cluster3_wGO2_df)),]
cluster3_wGO2_df <- cluster3_wGO2_df[,order(colnames(cluster3_wGO2_df))]

# using 0.01 as threshold
Clust3_threshold <- 0.01

imputed_Clust3_df <- as.data.frame(sapply(cluster3_wGO2_df, function(x){
   as.numeric(x > Clust3_threshold)
  }))
imputed_Clust3_df <- t(imputed_Clust3_df)
row.names(imputed_Clust3_df) <- row.names(cluster3_wGO2_df)

# Filter original GO matrix to include only the genes of interest and the GO terms from the imputed df
# Filter by row
cluster3_inputMat <- scerevisiae_GO_matrix_wide[scerevisiae_GO_matrix_wide$GeneID %in% rownames(imputed_Clust3_df),]
rownames(cluster3_inputMat) <- cluster3_inputMat[,1]
cluster3_inputMat[,1] = c()
# Filter by column
cluster3_inputMat <- cluster3_inputMat[,colnames(cluster3_inputMat) %in% colnames(imputed_Clust3_df)]
# Order by row names and column names
cluster3_inputMat <- cluster3_inputMat[order(rownames(cluster3_inputMat)),]
cluster3_inputMat <- cluster3_inputMat[,order(colnames(cluster3_inputMat))]


# Filter imputed_Clust3_df object to include the genes and GO terms of cluster1_inputMat object above
imputed_Clust3_trim <- imputed_Clust3_df[rownames(imputed_Clust3_df) %in% rownames(cluster3_inputMat),]

# Comparison between input df and resultant df
Clust3_inutVSimputed <- ifelse(cluster3_inputMat == imputed_Clust3_trim, TRUE, FALSE)

# Negative 1 values appear for threshold > 0.01
Clust3_subtract <- imputed_Clust3_trim - cluster3_inputMat
which(Clust3_subtract == -1)
```
